config/routes.rb
Rails.application.routes.draw do
  
  resources :curriculums
  get 'grad_list/index'

  get 'perfil/index'

  resources :graduations
  resources :internships
  root 'welcome#index'
  get 'welcome/index'
  get 'sessions/new'

  devise_for :user_companies

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/internship.rb
class Internship < ApplicationRecord
	belongs_to :user_company
	belongs_to :graduation
	has_many :curriculums

has_attached_file :curriculum, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :curriculum, :content_type => {:content_type => %w(image/jpeg image/jpg image/png application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)}
end

app/controllers/internships_controller.rb
class InternshipsController < ApplicationController
  before_action :set_internship, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user_company!, except:[:index,:show]
  # GET /internships
  # GET /internships.json
  def index
    if user_company_signed_in?
    @internships = Internship.where(user_company: current_user_company)
    elsif params[:search]
    @internships = Internship.where(graduation_id: params[:search])
    
    end
end 
  



  # GET /internships/1
  # GET /internships/1.json
  def show
  
  end

  # GET /internships/new
  def new
    @internship = Internship.new
  end

  # GET /internships/1/edit
  def edit
  end

  # POST /internships
  # POST /internships.json
  def create
    @internship = current_user_company.internships.build(internship_params)
    

    respond_to do |format|
      if @internship.save
        format.html { redirect_to @internship, notice: 'Internship was successfully created.' }
        format.json { render :show, status: :created, location: @internship }
      else
        format.html { render :new }
        format.json { render json: @internship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /internships/1
  # PATCH/PUT /internships/1.json
  def update
    respond_to do |format|
      if @internship.update(internship_params)
        format.html { redirect_to @internship, notice: 'Internship was successfully updated.' }
        format.json { render :show, status: :ok, location: @internship }
      else
        format.html { render :edit }
        format.json { render json: @internship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /internships/1
  # DELETE /internships/1.json
  def destroy
    @internship.destroy
    respond_to do |format|
      format.html { redirect_to internships_url, notice: 'Internship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_internship
      @internship = Internship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def internship_params
      params.require(:internship).permit(:office, :company, :cash, :duration, :description, :graduation_id, :graduation, :curriculum)
    end
end

app/helpers/internships_helper.rb
module InternshipsHelper
end

app/views/internships/_form.html.erb
<div class="container">
<%= form_for(internship) do |f| %>
  <% if internship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(internship.errors.count, "error") %> prohibited this internship from being saved:</h2>

      <ul>
      <% internship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :office %>
    <%= f.text_field :office %>
  </div>

  <div class="field">
    <%= f.label :company %>
    <%= f.text_field :company %>
  </div>

  <div class="field">
    <%= f.label :cash %>
    <%= f.text_field :cash %>
  </div>

  <div class="field">
    <%= f.label :duration %>
    <%= f.text_field :duration %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  
  <div class="field">
    <%= f.label :graduation_id %>
    <%= f.select :graduation_id, Graduation.all.collect { |c| [ c.name, c.id ] }, class:" browser-default", include_blank: true %>
  </div>
 
  
  <div class="waves-effect waves-light btn">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/internships/edit.html.erb
<div class="container">
<blockquote>
  <h2 style="text-align:center;font-size:25px;font-color:#424242">Editing Internshi</h2>
</blockquote>

<%= render 'form', internship: @internship %>
<div class="container">
<%= link_to 'Show', @internship, class: "waves-effect waves-light btn"  %> |
<%= link_to 'Back', internships_path, class: "waves-effect waves-light btn"  %>
</div></div>

app/views/internships/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<blockquote>
  <h2 style="text-align:center;font-size:30px;font-color:#424242">Internships</h2>
</blockquote>
<table class="responsive-table">
  <thead>
    <tr>
      <th>Office</th>
      <th>Company</th>
      <th>Cash</th>
      <th>Duration</th>
      <th>Description</th>
      <th>Graduation</th>
      <th>Curriculums</th>
      <th colspan="3"></th>
    </tr>
   
  </thead>

  <tbody>
    <% @internships.each do |internship| %>
      <tr>
        <td><%= internship.office %></td>
        <td><%= internship.company %></td>
        <td><%= internship.cash %></td>
        <td><%= internship.duration %></td>
        <td><%= internship.description %></td>
        <td><%= internship.graduation.name%></td>
        <% if !user_company_signed_in?%>
        
        <td><%= file_field_tag :curriculum %></td>
        <td><%= submit_tag "Enviar" %></td>
        
        <%end%>
        <% if user_company_signed_in?%>
        <td> <%= internship.curriculum%></td>
        <%end%>
        <% if user_company_signed_in?%>
        <td><%= link_to 'Show', internship %></td>
        <td><%= link_to 'Edit', edit_internship_path(internship) %></td>
        <td><%= link_to 'Apagar', internship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_company_signed_in?%>
<%= link_to 'New Internship', new_internship_path, class: "waves-effect waves-light btn" %>
<%end%>
</div>

app/views/internships/new.html.erb
<div class="container">
<blockquote>
  <h2 style="text-align:center;font-size:30px;font-color:#424242">Cadastrar estágio</h2>
</blockquote>

<%= render 'form', internship: @internship %>
<div class ="container">
<%= link_to 'Back', internships_path, class: "waves-effect waves-light btn" %>
</div></div>

app/views/internships/show.html.erb
<table class="responsive-table">
<table class="centered">
<table class="highlight" >
<p id="notice"><%= notice %></p>

<p>
  <strong>Office:</strong>
  <%= @internship.office %>
</p>

<p>
  <strong>Company:</strong>
  <%= @internship.company %>
</p>

<p>
  <strong>Cash:</strong>
  <%= @internship.cash %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @internship.duration %>
</p>

<p>
  <strong>Description:</strong>
  <%= @internship.description %>
</p>
<p>
  <strong>Graduation:</strong>
  <%= @internship.graduation%>
</p>
<p>
  <strong>Curriculum:</strong>
  <%= @internship.curriculum%>
</p>

 
 

<%= link_to 'Edit', edit_internship_path(@internship) %> |
<%= link_to 'Back', internships_path %>
</table></table></table>