config/routes.rb
Rails.application.routes.draw do
  
  resources :curriculums
  get 'grad_list/index'

  get 'perfil/index'

  resources :graduations
  resources :internships
  root 'welcome#index'
  get 'welcome/index'
  get 'sessions/new'

  devise_for :user_companies

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/graduation.rb
class Graduation < ApplicationRecord
	has_many :internships

	
end

app/controllers/graduations_controller.rb
class GraduationsController < ApplicationController
  before_action :set_graduation, only: [:show, :edit, :update, :destroy]
  
  # GET /graduations
  # GET /graduations.json
  def index
    @graduations = Graduation.all
  end

  # GET /graduations/1
  # GET /graduations/1.json
  def show
  end

  # GET /graduations/new
  def new
    @graduation = Graduation.new
  end

  # GET /graduations/1/edit
  def edit
  end

  # POST /graduations
  # POST /graduations.json
  def create
    @graduation = Graduation.new(graduation_params)

    respond_to do |format|
      if @graduation.save
        format.html { redirect_to @graduation, notice: 'Graduation was successfully created.' }
        format.json { render :show, status: :created, location: @graduations }
      else
        format.html { render :new }
        format.json { render json: @graduation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /graduations/1
  # PATCH/PUT /graduations/1.json
  def update
    respond_to do |format|
      if @graduation.update(graduation_params)
        format.html { redirect_to @graduation, notice: 'Graduation was successfully updated.' }
        format.json { render :show, status: :ok, location: @graduation }
      else
        format.html { render :edit }
        format.json { render json: @graduation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /graduations/1
  # DELETE /graduations/1.json
  def destroy
    @graduation.destroy
    respond_to do |format|
      format.html { redirect_to graduations_url, notice: 'Graduation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_graduation
      @graduation = Graduation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def graduation_params
      params.require(:graduation).permit(:name)
    end
end

app/helpers/graduations_helper.rb
module GraduationsHelper
end

app/views/graduations/_form.html.erb
<%= form_for(graduation) do |f| %>
  <% if graduation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(graduation.errors.count, "error") %> prohibited this graduation from being saved:</h2>

      <ul>
      <% graduation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/graduations/edit.html.erb
<h1>Editing Graduation</h1>

<%= render 'form', graduation: @graduation %>

<%= link_to 'Show', @graduation %> |
<%= link_to 'Back', graduations_path %>

app/views/graduations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Graduations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @graduations.each do |graduation| %>
        <tr>
        <td><%= graduation.name%></td>
        <td><%= link_to 'Show', graduation %></td>
        <td><%= link_to 'Edit', edit_graduation_path(graduation) %></td>
        <td><%= link_to 'Destroy', graduation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Graduation', new_graduation_path %>

app/views/graduations/new.html.erb
<h1>New Graduation</h1>

<%= render 'form', graduation: @graduation %>

<%= link_to 'Back', graduations_path %>

app/views/graduations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_graduation_path(@graduation) %> |
<%= link_to 'Back', graduations_path %>