config/routes.rb
Rails.application.routes.draw do
  
  resources :curriculums
  get 'grad_list/index'

  get 'perfil/index'

  resources :graduations
  resources :internships
  root 'welcome#index'
  get 'welcome/index'
  get 'sessions/new'

  devise_for :user_companies

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mural</title>
    <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/icon?family=Material+Icons"%>
  <!--Import materialize.css-->
  <%= stylesheet_link_tag "css/materialize.min.css"%>
    <%= favicon_link_tag %>

  <!-- Compiled and minified CSS -->
  <%=stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css"%>

  <!-- Compiled and minified JavaScript -->
   <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"%>
   <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
  <%= javascript_include_tag "https://code.jquery.com/jquery-2.1.1.min.js", type:"text/javascript"%>
  <%= javascript_include_tag "js/materialize.min.js", type:"text/javascript"%>

    <div class="navbar-fixed">
     <nav  class="extended-nav", role="navigation" >
      <div class="nav-wrapper">
        
         <a href="http://localhost:3000/welcome/index"><i class="material-icons brand-logo center">supervisor_account</i></a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
            <% if !current_user_company %>
                <li><%= link_to "Cadastre sua empresa", new_user_company_registration_path%></li>
                <li><%= link_to "Entrar", new_user_company_session_path%></li>
            <% end %>
            
            <% if user_company_signed_in? %>
              <li><%= link_to "Perfil", perfil_index_path %></li>
              <li><%= link_to "Adicionar estágios", new_internship_path%></li>
              <li><%= link_to "Meus anúncios", internships_path%></li>
              <li><%= link_to 'Sair', destroy_user_company_session_path, :method => :delete%></li>
            <% end %>
          </ul>
          <!--
            <ul class="side-nav" id="mobile-demo">
            <% if !current_user_company %>
                <li><%= link_to "Cadastre sua empresa", new_user_company_registration_path%></li>
                <li><%= link_to "Entrar", new_user_company_session_path%></li>
            <% end %>
            
            <% if user_company_signed_in? %>
              <li><%= link_to "Perfil", perfil_index_path %></li>
              <li><%= link_to "Adicionar estágios", new_internship_path%></li>
              <li><%= link_to "Meus anúncios", internships_path%></li>
              <li><%= link_to 'Sair', destroy_user_company_session_path, :method => :delete%></li>
            <% end %>
          </ul>-->

      </div>
    </nav>
    </div>
    
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
 

    </html>